<?php
/**
 * ConfigApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brain Commerce Ingestor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConfigApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConfigApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteDataByKeyFromConfigTableV1ConfigConfigByKeyDelete
     *
     * Delete Data By Key From 'Config' Table..
     *
     */
    public function testDeleteDataByKeyFromConfigTableV1ConfigConfigByKeyDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllDataFromConfigTableV1ConfigConfigGetAllGet
     *
     * Get All Data From Config Table..
     *
     */
    public function testGetAllDataFromConfigTableV1ConfigConfigGetAllGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDataByKeyFromConfigTableV1ConfigConfigGetByKeyGet
     *
     * Get Data By Key From Config Table..
     *
     */
    public function testGetDataByKeyFromConfigTableV1ConfigConfigGetByKeyGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for insertDataToConfigTableV1ConfigConfigPost
     *
     * Insert Data To Config Table..
     *
     */
    public function testInsertDataToConfigTableV1ConfigConfigPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
