<?php
/**
 * FaqApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Brain Commerce Ingestor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FaqApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FaqApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createFaqByQuestion
     *
     * Create Faq By Question.
     *
     */
    public function testCreateFaqByQuestion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createFaqCollection
     *
     * Create Faq Collection.
     *
     */
    public function testCreateFaqCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFaqByInternalId
     *
     * Delete Faq By Internal Id.
     *
     */
    public function testDeleteFaqByInternalId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFaqByQuestion
     *
     * Delete Faq By Question.
     *
     */
    public function testDeleteFaqByQuestion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFaqCollection
     *
     * Delete Faq Collection.
     *
     */
    public function testDeleteFaqCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllFaqs
     *
     * Get All Faqs.
     *
     */
    public function testGetAllFaqs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFaqByQuestion
     *
     * Get Faq By Question.
     *
     */
    public function testGetFaqByQuestion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFaqCollectionExists
     *
     * Check If Faq Collection Exists..
     *
     */
    public function testGetFaqCollectionExists()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for importMultipleFaqs
     *
     * Import Multiple Faqs.
     *
     */
    public function testImportMultipleFaqs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resetFaqCollection
     *
     * Deletes All Faq From Collection.
     *
     */
    public function testResetFaqCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateFaqByQuestion
     *
     * Update Faq By Question.
     *
     */
    public function testUpdateFaqByQuestion()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
