<?php
/**
 * FaqApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * luma store api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FaqApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FaqApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for checkIfFAQCollectionExistsV1FaqCollectionExistsGet
     *
     * Check If Faq Collection Exists..
     *
     */
    public function testCheckIfFAQCollectionExistsV1FaqCollectionExistsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createFAQByQuestionV1FaqQuestionPost
     *
     * Create Faq By Question.
     *
     */
    public function testCreateFAQByQuestionV1FaqQuestionPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createFAQCollectionV1FaqCollectionPost
     *
     * Create Faq Collection.
     *
     */
    public function testCreateFAQCollectionV1FaqCollectionPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFAQByInternalIdV1FaqByInternalIdInternalIdDelete
     *
     * Delete Faq By Internal Id.
     *
     */
    public function testDeleteFAQByInternalIdV1FaqByInternalIdInternalIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFAQByQuestionV1FaqQuestionDelete
     *
     * Delete Faq By Question.
     *
     */
    public function testDeleteFAQByQuestionV1FaqQuestionDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFAQCollectionV1FaqCollectionDelete
     *
     * Delete Faq Collection.
     *
     */
    public function testDeleteFAQCollectionV1FaqCollectionDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletesAllFAQFromCollectionV1FaqResetCollectionDelete
     *
     * Deletes All Faq From Collection.
     *
     */
    public function testDeletesAllFAQFromCollectionV1FaqResetCollectionDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for gestFAQByQuestionV1FaqQuestionGet
     *
     * Gest Faq By Question.
     *
     */
    public function testGestFAQByQuestionV1FaqQuestionGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllFAQsV1FaqGet
     *
     * Get All Faqs.
     *
     */
    public function testGetAllFAQsV1FaqGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for importMultipleFAQsV1FaqPost
     *
     * Import Multiple Faqs.
     *
     */
    public function testImportMultipleFAQsV1FaqPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateFAQByQuestionV1FaqQuestionPut
     *
     * Update Faq By Question.
     *
     */
    public function testUpdateFAQByQuestionV1FaqQuestionPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
