<?php
/**
 * ProductApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * luma store api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProductApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProductApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createProductCollectionV1ProductCollectionPost
     *
     * Create Product Collection.
     *
     */
    public function testCreateProductCollectionV1ProductCollectionPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteProductCollectionV1ProductCollectionDelete
     *
     * Delete Product Collection.
     *
     */
    public function testDeleteProductCollectionV1ProductCollectionDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllProductsV1ProductGet
     *
     * Get All Products.
     *
     */
    public function testGetAllProductsV1ProductGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductCollectionV1ProductResetCollectionDelete
     *
     * Get Product Collection.
     *
     */
    public function testGetProductCollectionV1ProductResetCollectionDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProductV1ProductSkuGet
     *
     * Get Product.
     *
     */
    public function testGetProductV1ProductSkuGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ingestProductV1ProductSkuPost
     *
     * Ingest Product.
     *
     */
    public function testIngestProductV1ProductSkuPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ingestProductV1ProductSkuPut
     *
     * Ingest Product.
     *
     */
    public function testIngestProductV1ProductSkuPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for ingestProductsV1ProductPost
     *
     * Ingest Products.
     *
     */
    public function testIngestProductsV1ProductPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
