<?php
/**
 * ReviewsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * luma store api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.7.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReviewsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReviewsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for checkIfProductReviewSchemaExistsV1ReviewsIsSchemaExistsGet
     *
     * Check If Product Review Schema Exists.
     *
     */
    public function testCheckIfProductReviewSchemaExistsV1ReviewsIsSchemaExistsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOneReviewBySKUV1ReviewsPost
     *
     * Create One Review By Sku.
     *
     */
    public function testCreateOneReviewBySKUV1ReviewsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createSchemaAndProductReviewTableV1ReviewsSchemaPost
     *
     * Create Schema And Product Review Table.
     *
     */
    public function testCreateSchemaAndProductReviewTableV1ReviewsSchemaPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAllReviewsV1ReviewsDelete
     *
     * Delete All Reviews.
     *
     */
    public function testDeleteAllReviewsV1ReviewsDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteReviewsByProductSKUV1ReviewsSkuDelete
     *
     * Delete Reviews By Product Sku.
     *
     */
    public function testDeleteReviewsByProductSKUV1ReviewsSkuDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAllReviewsV1ReviewsGet
     *
     * Get All Reviews.
     *
     */
    public function testGetAllReviewsV1ReviewsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReviewsBySKUV1ReviewsSkuGet
     *
     * Get Reviews By Sku.
     *
     */
    public function testGetReviewsBySKUV1ReviewsSkuGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
